apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-pull-information
  namespace: weavek8sops
spec:
  encryptedData:
    password: AgAE1Tc5oNpVhm4nsPlMcriSvL75Ip1+YiM3H1JIxUjyxS4KbRoSRbM8ly/Xfaa7gi6TgG113BGbgvEWlrL47E/UG+F/uf7wkfpYzSSOvfkOAkrkBJJC2khtuc8bOb5NHYgq3zz88s6EVG8J9yqcGGsmTjQopQBFaYsCh+cG2ayPtf2gKC3y7yeF+VScjTpsne+2cjuZHA5ebhRqhTb0tsq++BbP1PnERVRKbeCDSSVlvIuOA8c8AqpCPnuX7UGzSM2zQB+32u6Vd+ZlltM+65B7YSyLRa7Y99Cz1LDhJt7zCg5yDkICpTFJRW0Y+ouXQ4Igvbn0Mfo966emYotSG+BQoCljB4L4Ez3rz7pQq2Z0YAug2cV6tqWMPLMuRTSiaffpOjJ/SbHfIj4N4ilg4Q/A7C9+PSPbUew/xLnHI2htzQa+/t+iFGWxn3NvGE/ysdBGBj7cQmcDKvKqlPGnS8ny8NTRLMpQiTV2Tus2mYKej/s67DX6L2jt5t0X8WOs8OJkv8XMzdXh0Ooi2pzxlP06H+XHzPcvbPnkXhFbmZeo7xUV06GMfb7p6H5o4cW/Mcf5xgiKpXPbeSlG9rAvKhEyP+Jlb6SUJvr/SjNiJ/W2LTwHHE0owEy3FpdDRi74N7YrN1wzU0ab7mEXEkOOUcgBNc5iVnYxRB3f36NBcP7W2K+Clnu5U3OPFI4UDfhZWl5ASndlrki2ZdY=
    username: AgAN2+pIzA+spB0V3TdysHi+sMHxPeakb+mxIWzBBHliSBQqAbvcWmNy7MzEtzoZR76NQLGrW+Q9IWGRyX+pv3r1iCsxf9GQlMK/RRGbFgTPDH4S3sHLB3fHty8MYd2Leu4iwLuJYogpBroecL5Nqo8fYLKCjyx+s2UyeU/tUXRrIEAWS4T/PdnbsWk6jeAYlG9rIkzot1pn0FwyX8rpq1FcoGyATHS1lijIdeN8OfSaXExYrA0nEM83J6MBT5l5XLicceAgdLRvGZzklprGxshw9T30e54RpuAElzCGHqNZt/W8A1DXc2L9LzIujK91kd9A5AQ4yoImZ2BFUP+vT2/1V4C8hrUarV0BaUvQJegn6tW/jHfZfnm8YfTrkeoFrJzjbvO3uykRsNni4Y8Q0PGX/86pkWhc+X8pwCoDPe0qbmt1VVKmQ2958yJSyqcdKCxpn3+qoc9Ve5ith0MV6yO2O9kIwZOVSHhuSkP88F2AFehj6rqLeHX69Gn2lplaQ8JRUcwjyPA8wgjbHN9du6/l4iAiaAFORtzjay08YHlchV5NGITUivk55be2tGwFFHBoTHmuHsh5jXcAjNipACABrSOT4+0Lp+63S66l7VviMvl1GzukFTpIUZYCvuCmRXpIe8cz76i5AYQv6QqzjtxMQq2NEsvRJQyt9HNpLRy2aWEgKZ7WLLiPfpH1Ch8KY2sCBSApJ4VmSs0=
  template:
    metadata:
      creationTimestamp: null
      name: image-pull-information
      namespace: weavek8sops
    type: Opaque
status: {}

