apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-pull-information
  namespace: weavek8sops
spec:
  encryptedData:
    password: AgCAck23PEfFnjYbIJdlslxrxpA1Nire0sgo2keJLXMkeXymPCgtaQTEmYszuVCZA9ycRR8AYxOreGbI/3uQJUNV4aSsjTgL98OcZvyDXbmoKectQIOmr1PLg/4Wx0hklEYafjrBTqkb7YR4OtzPCiayOPhd0W9IBI9+rogDPPvwYWkAfMBtyXhhUVM1/yBnXaHB5/5OcTFwoYKXrO06xqBbrSjRafqbSXsGttYGvHi5+YzSn92+6rtj8Fud0CY8+/xZ93wFAJkXl8HEMiU2hPXNBmPQ0cnNOejCHNqBTyxgES4ZlRwQtOAOKKZ3j4GEpDogOZUyVxN43cL2FEIJ3/BZXIR41DMkiGiLPk90SuU/qycd1zNHWIHXcKNb8rvkpUfPgGv2trm7HVymkKZY4f2TtnqdLeLaJZwsmCJPYvvkyKa6u/+6a6Nl2W/YIRblL1gzSj3C3e9iZxnaLINJ+I/jt/kC4ey0lVptSZlasbBpWDjbabGrhzZWqNoQ322dmlkOhfZbdwVB8yUY92232yUqpKdYla1U5ubY8mCWZ3mQ0T8wXgMbalykyAaZgKOekGV46vxdVCfoEqQ1/bh4vXCa1Ol83TJUrSUFD4tw5sxKucHIuswhbsxKsU6pZTrFTrgi6Yfv0zk0ZiyS/aM/2dLxmj1A/Bd+m/hGgPTt6YeZUrxi0CKt0dLw8yKrpbd7+Nd7/J7NLMZNBxE=
    username: AgCDQrjFX0wUggyxWE+iph8K+HxwZsV9/xyZ/h8WykmPipL59twSV/8hXtWLFeypkX2WcLM6y/6+bQ+sxExFcdwYwiW7T2mD91kXMkU1+OUKN3SmsKZFgD9I+C3U4CHFG0uGLaMiUCbclU9oSHyeuT6UWH96WvQN01SJPKcLlGt4kT+/yeIZtRZWhBtbBFFB7ELBStn8GoW37ePMJBkXBaccpH2eIA1YqoScIoV5RpTFWpX/u0MREgWeW/j5WkHxNI+kS14XnsTWLdiG0iMsmdEIGBOc4YqmF+IlSZYVIky+6Rxy2MhVo1MGYrcFsqQU3avVprPS8T8EJhiWgbsqhJtxpVShTH+evucgXTreibgyuah8sYM5smE3TgR7dSLATvowIFmgtFTMkTfVx6eEGcq7JA1Xh+VVIjm1Fsr1JFvgHiJCbMgOX3f86Ja9DgwNfY2zzYk1mCuqPV2fcEsLFqd4mTb9Ap9MN0pOS5SjWTLYPD1dSap4Ehn9bUF/w4/8FbTkPxf2BSOKfWCu2+0ZwyGbBbnDKdPnkgl+hW+SPUtDz+s/oHQWUYVqbkUStbBs4sr95jcmeviE9dYYsPVEwcbh687CjzT6vOIizXNXrciMkZl334y+fBAmeWZ07WjSxgh2xw305mbPW+BL1jbi3+Pw0g14TRyr/EJDGW3ULB9ebqKgrN7ZSTqGiw8sTsPgJ503DgteTjU08rc=
  template:
    metadata:
      creationTimestamp: null
      name: image-pull-information
      namespace: weavek8sops
    type: Opaque
status: {}

